
export const SET_LIST_LOP_MON = "SET_LIST_LOP_MON";

export const SET_LOP_MON_DETAIL = "SET_LOP_MON_DETAIL";

export const SET_LOADING_TABLE = "SET_LOADING_TABLE";

export const SET_VALUE_SEARCH = "SET_VALUE_SEARCH";

export const SET_TOTAL_ELEMENT = "SET_TOTAL_ELEMENT";